[project]
name = "infra"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-aws-lambda-python-alpha>=2.261.0a0",
    "aws-cdk-lib>=2.261.0",
    "constructs>=10.6.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.15.21",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
